### ISSUE TITLE
osdctl doesnt work

### ISSUE THREAD

**Issue by georgettica** [drewandersonnz/ocm-container#22]
when running 

```
osdctl clusterdeployment list
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by georgettica** [comment]
I think that what is used is https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/#using-kubectl-to-start-a-proxy-server

**Comment by iamkirkbater** [comment]
osdctl requires a connection into a hive.  So in this case you'd need to gain access to a v4 hive shard, and then run the osdctl commands against that.

We are talking about possibly leveraging OCM to integrate this so that you don't have to do any of that, but the biggest problem with that right now is having to tunnel and authenticate against the hive shards.

**Comment by georgettica** [comment]
so currently I talked to james on the issue and we solved this for now.. we can reraise this issue when the time comes..

closing for now
